<a href="https://colab.research.google.com/github/CyberKaps/AI-ML/blob/main/class_4_intro_to_tensor_and_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import time
import math


#check if GUP is available or not
print(f"pytorch version: {torch.__version__}")
print(f"GPU available: {torch.cuda.is_available()}")

if torch.cuda.is_available():
  print(f"GPU Name: {torch.cuda.get_device_name(0)}")
else:
  print("No GPU available")

print("\nsetup complete")

pytorch version: 2.10.0+cu128
GPU available: True
GPU Name: Tesla T4

setup complete


# 1. Tensors

In [26]:
# A scalar - just a number
kalpesh_age = torch.tensor(21.0)

In [27]:
print(kalpesh_age)

tensor(21.)


In [ ]:
print(f"The value of kalpesh_age is: {kalpesh_age}")
print(f"The data type of kalpesh_age is: {kalpesh_age.dtype}")

The value of kalpesh_age is: 21.0
The data type of kalpesh_age is: torch.float32


In [38]:
# A vector - a list of numbers
vector = torch.tensor([1.0, 2.0, 3.0, 4.0])

In [39]:
print(vector)

tensor([1., 2., 3., 4.])


In [37]:
print(vector.dim())

1


In [25]:
print(kalpesh_age.dim())

0


In [28]:
# A matrix - grid of numbers
matrix = torch.tensor([[1, 2, 3],
                      [4, 5, 6]])
print(f"Matrix:\n{matrix}")
print(f"  Shape: {matrix.shape}")   # torch.Size([2, 3])
print(f"  Dimensions: {matrix.dim()}") #

Matrix:
tensor([[1, 2, 3],
        [4, 5, 6]])
  Shape: torch.Size([2, 3])
  Dimensions: 2


In [31]:
# A 3D tensor - a cube of numbers
tensor_3d = torch.zeros(2, 3, 4)
print(f"3D Tensor shape: {tensor_3d.shape}")  # [2, 3, 4]
print(f"  Dimensions: {tensor_3d.dim()}")   # 3

3D Tensor shape: torch.Size([2, 3, 4])
  Dimensions: 3


In [45]:
# A 4D tensor - like a batch going through multi-head attentions
tensor_4d = torch.zeros(8,12, 3, 64)
print(f"4D Tensor shape: {tensor_4d.shape}")
print(f"  Dimensions: {tensor_4d.dim()}")
# print(tensor_4d)

4D Tensor shape: torch.Size([8, 12, 3, 64])
  Dimensions: 4


In [40]:
# If you're passing numbers as dimensions → zeros()
# If you're passing numbers as actual data → tensor()

# 1.2 Creating Tensors - Many ways


In [59]:
# zeros and ones

z = torch.zeros(3, 4)   #3x4 matrix of zeros
o = torch.ones(2, 5)    #2x5 matrix of ones


# random (normal distribution) - this is how weights start!
r = torch.randn(3, 3)    # random value, mean=0, std=1
print("Random matrix (this is how neural network weights begin):")
print(r)
print()

# from a range
seq = torch.arange(0, 10)  #[0, 1, 2, ..., 9]
print(f"Sequence: {seq}")

# Linspace - evenly spaced
lin = torch.linspace(0, 1, 5)   # 5 values of from 0 to 1
print(f"Linspace: {lin}")

Random matrix (this is how neural network weights begin):
tensor([[ 0.9359, -0.4648, -0.2286],
        [ 0.6397, -0.1357, -0.0800],
        [ 1.3298,  0.8691, -0.9183]])

Sequence: tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
Linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])


# 1.3 Shape is Everything

In [ ]:
# Real-world shapes in deep learning